export type DailyHuntSeedLead = {
  id: string;
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
  category: string;
  target: string;
  address: string;
  developer_or_owner: string | null;
  size: string;
  units: number | null;
  status: string;
  pitch_angle: string;
  best_contact_path: string;
  source: string | null;
  imported_at: string;
};

export const DAILY_HUNT_SEED_IMPORTED_AT = '2026-05-25T18:00:00.000Z';

export const DAILY_HUNT_SEED_LEADS: DailyHuntSeedLead[] = [
    {
        "id":  "fd7ef85f-3b34-4b0a-9d99-1cdf16920ba0",
        "priority":  "HIGH",
        "category":  "New Dev — Sponsor-to-Board Transition",
        "target":  "The Harper",
        "address":  "310 East 86th Street Manhattan",
        "developer_or_owner":  "Naftali Group",
        "size":  "24 units",
        "units":  24,
        "status":  "Closings underway nearly sold",
        "pitch_angle":  "Board formation imminent — pitch transition mgmt",
        "best_contact_path":  "LinkedIn / brokerage network to Miki Naftali CEO",
        "source":  "Kimi research May 25 2026",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "56599b77-8de6-42ed-ab77-fef3b7399465",
        "priority":  "HIGH",
        "category":  "New Dev — Sponsor-to-Board Transition",
        "target":  "126 East 86th Street",
        "address":  "126 East 86th Street Manhattan",
        "developer_or_owner":  "Rybak Development",
        "size":  "19 units",
        "units":  19,
        "status":  "Closings commenced Sept 2024",
        "pitch_angle":  "Sponsor still holding units — pitch full PM takeover",
        "best_contact_path":  "Direct email Rybak development team",
        "source":  "Kimi research May 25 2026",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "e3bcae9e-1669-40ac-a06f-d669425faafe",
        "priority":  "HIGH",
        "category":  "New Dev — Sponsor-to-Board Transition",
        "target":  "255 East 77th Street",
        "address":  "255 East 77th Street Manhattan",
        "developer_or_owner":  "Naftali Group + Robert A.M. Stern",
        "size":  "62 units",
        "units":  62,
        "status":  "Under construction est 2026",
        "pitch_angle":  "Pre-completion PM pitch to sponsor",
        "best_contact_path":  "Miki Naftali / RAMSA team",
        "source":  "Kimi research May 25 2026",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "79494eaf-f39a-42f3-82a6-3ee7e43ee575",
        "priority":  "HIGH",
        "category":  "New Dev — Sponsor-to-Board Transition",
        "target":  "140 Jane Street",
        "address":  "140 Jane Street West Village",
        "developer_or_owner":  "Aurora Capital Associates",
        "size":  "14 units",
        "units":  14,
        "status":  "Under construction est 2026",
        "pitch_angle":  "Boutique luxury — perfect Camelot fit",
        "best_contact_path":  "Aurora principals — RE event networking",
        "source":  "Kimi research May 25 2026",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "1ab2b1d3-eb16-4a51-aff9-bf9674484c71",
        "priority":  "HIGH",
        "category":  "New Dev — Sponsor-to-Board Transition",
        "target":  "501 East 81st Street",
        "address":  "501 East 81st Street Manhattan",
        "developer_or_owner":  "Rybak Development",
        "size":  "9 units",
        "units":  9,
        "status":  "Completion est 2026",
        "pitch_angle":  "Small luxury — Camelot sweet spot",
        "best_contact_path":  "Rybak development team",
        "source":  "Kimi research May 25 2026",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "35b723d2-953f-4d32-a989-540895d8097d",
        "priority":  "HIGH",
        "category":  "New Dev — Sponsor-to-Board Transition",
        "target":  "80 Clarkson",
        "address":  "80 Clarkson Street West Village",
        "developer_or_owner":  "Zeckendorf Dev / Atlas Capital / Baupost",
        "size":  "TBD",
        "units":  null,
        "status":  "Under construction est 2026",
        "pitch_angle":  "High-profile founder-level outreach to William Zeckendorf",
        "best_contact_path":  "High-end brokerage connection to Zeckendorf",
        "source":  "Kimi research May 25 2026",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "81d93635-34d1-4e42-80e2-899cfe581d08",
        "priority":  "HIGH",
        "category":  "New Dev — Sponsor-to-Board Transition",
        "target":  "1122 Madison Avenue",
        "address":  "1122 Madison Avenue Manhattan",
        "developer_or_owner":  "Legion Investment Group + Nahla Capital",
        "size":  "26 units",
        "units":  26,
        "status":  "Completion est 2027",
        "pitch_angle":  "$10M+ units ultra-luxury PM pitch",
        "best_contact_path":  "Direct to Legion / Nahla principals",
        "source":  "Kimi research May 25 2026",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "c6fd2fe8-35d4-4362-a180-9aa6c6a69e77",
        "priority":  "HIGH",
        "category":  "New Dev — Sponsor-to-Board Transition",
        "target":  "985 Fifth Avenue",
        "address":  "985 Fifth Avenue Manhattan",
        "developer_or_owner":  "Spitzer Enterprises",
        "size":  "26 units",
        "units":  26,
        "status":  "Completion est 2027",
        "pitch_angle":  "Museum Mile prestige client",
        "best_contact_path":  "Direct to Spitzer Enterprises",
        "source":  "Kimi research May 25 2026",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "3b8bea39-4fac-4704-88cf-db26adf0d09f",
        "priority":  "HIGH",
        "category":  "New Dev — Sponsor-to-Board Transition",
        "target":  "288 East 88th Street",
        "address":  "288 East 88th Street Manhattan",
        "developer_or_owner":  "Alchemy Properties",
        "size":  "45 units",
        "units":  45,
        "status":  "Topped out May 2025 sales launching",
        "pitch_angle":  "Pitch PM before board forms",
        "best_contact_path":  "Direct to Alchemy Properties",
        "source":  "Kimi research May 25 2026",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "f10b27fa-6f89-4286-b6b2-d2241f3f766b",
        "priority":  "HIGH",
        "category":  "New Dev — Brooklyn",
        "target":  "205 Montague Street",
        "address":  "205 Montague Street Brooklyn Heights",
        "developer_or_owner":  "Landau Properties + Third Millennium + Midtown Equities",
        "size":  "46 condos + 90 rentals",
        "units":  null,
        "status":  "Demolition/construction begins 2026",
        "pitch_angle":  "Mixed-use — pitch full PM for condo portion",
        "best_contact_path":  "Landau principals — Brooklyn dev community",
        "source":  "Kimi research May 25 2026",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "aa6a9c2a-9366-402c-a044-97ff6aa9471f",
        "priority":  "HIGH",
        "category":  "New Dev — Brooklyn",
        "target":  "One Wharf Way (Williamsburg Wharf Phase 2)",
        "address":  "Williamsburg waterfront",
        "developer_or_owner":  "Two Trees Management / COOKFOX",
        "size":  "2 towers 285+ ft",
        "units":  null,
        "status":  "~65% sold construction underway",
        "pitch_angle":  "Sponsor handoff as sales complete",
        "best_contact_path":  "Jed Walentas Two Trees — Brooklyn RE network",
        "source":  "Kimi research May 25 2026",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "f3a24b3a-d774-44a6-8d80-801214ac6878",
        "priority":  "HIGH",
        "category":  "New Dev — Brooklyn",
        "target":  "Bergen 489 Bergen",
        "address":  "489 Bergen Street Boerum Hill",
        "developer_or_owner":  "Avdoo \u0026 Partners Development",
        "size":  "105 units",
        "units":  105,
        "status":  "Active sales 7 contracts signed Feb 2026 ($1.5M-$3.4M)",
        "pitch_angle":  "Sponsor holding inventory — pitch rental mgmt + board transition",
        "best_contact_path":  "Avdoo \u0026 Partners directly",
        "source":  "The Real Deal",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "817ce0a1-aaee-4c48-87e3-2694a89ed90d",
        "priority":  "HIGH",
        "category":  "New Dev — Brooklyn",
        "target":  "19-29 Clay Street",
        "address":  "19-29 Clay Street Greenpoint",
        "developer_or_owner":  "Investmates",
        "size":  "68 units",
        "units":  68,
        "status":  "Construction financing secured $81M 14-story luxury",
        "pitch_angle":  "Pre-completion PM pitch",
        "best_contact_path":  "Direct to Investmates",
        "source":  "Multi-Housing News",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "e48d5a42-9924-45c2-9d87-f62ca47c37e7",
        "priority":  "MEDIUM",
        "category":  "New Dev — Brooklyn",
        "target":  "One Domino Square",
        "address":  "346 Kent Avenue Williamsburg",
        "developer_or_owner":  "Two Trees Management",
        "size":  "Mixed-use",
        "units":  null,
        "status":  "Active luxury amenities unveiled",
        "pitch_angle":  "Two Trees multi-project relationship",
        "best_contact_path":  "Jed Walentas Two Trees",
        "source":  "Brooklyn Press",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "a443800f-f423-45cd-9abc-b7bce8028752",
        "priority":  "MEDIUM",
        "category":  "New Dev — Brooklyn",
        "target":  "One South First",
        "address":  "1 South 1st Street Williamsburg",
        "developer_or_owner":  "Two Trees Management",
        "size":  "Mixed-use",
        "units":  null,
        "status":  "Active luxury amenities",
        "pitch_angle":  "Two Trees multi-project relationship",
        "best_contact_path":  "Jed Walentas Two Trees",
        "source":  "Brooklyn Press",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "8edcd227-76fe-4d5f-99e9-e255d6057954",
        "priority":  "HIGH",
        "category":  "New Dev — Manhattan boutique",
        "target":  "220 East 9th Street",
        "address":  "220 East 9th Street East Village",
        "developer_or_owner":  "Compass Development Marketing",
        "size":  "18 units",
        "units":  18,
        "status":  "16 of 18 contracts signed Feb 2026",
        "pitch_angle":  "Nearly sold out — board formation imminent",
        "best_contact_path":  "Compass Development Marketing",
        "source":  "Marketproof",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "5735d696-be36-4dc8-a1f9-2bec5f55850e",
        "priority":  "HIGH",
        "category":  "New Dev — Manhattan boutique",
        "target":  "227 West 19th Street",
        "address":  "227 West 19th Street Chelsea",
        "developer_or_owner":  "Round Square Builders + DXA Studio",
        "size":  "8 units",
        "units":  8,
        "status":  "Topped out private fitness center + rooftop",
        "pitch_angle":  "Completion 2026 — direct sponsor outreach",
        "best_contact_path":  "Round Square Builders",
        "source":  "CityRealty",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "e154405e-2238-40f5-8484-0c4e04b4473b",
        "priority":  "HIGH",
        "category":  "New Dev — Queens LIC",
        "target":  "Paragon (Paint Factory site)",
        "address":  "LIC",
        "developer_or_owner":  "ZD Jasper (from Quadrum/Baron/Simon JV)",
        "size":  "186 units studio-4BR",
        "units":  186,
        "status":  "Topped out 23 stories completion 2026",
        "pitch_angle":  "Mixed-use condo + retail PM pitch",
        "best_contact_path":  "ZD Jasper directly",
        "source":  "CityRealty",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "b7ace8aa-1a68-433d-8c68-90bbc45dda80",
        "priority":  "HIGH",
        "category":  "New Dev — Queens LIC",
        "target":  "Loft 21",
        "address":  "11-50 45th Road LIC",
        "developer_or_owner":  "Century Development",
        "size":  "66 units 6 stories",
        "units":  66,
        "status":  "Completion est 2026 27 parking spaces",
        "pitch_angle":  "Boutique LIC — direct sponsor outreach",
        "best_contact_path":  "Century Development",
        "source":  "CityRealty",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "dc9a4218-8ef3-4bfc-b79a-5599dfeecf86",
        "priority":  "HIGH",
        "category":  "New Dev — Queens LIC",
        "target":  "Urban 21",
        "address":  "46-30 21st Street LIC",
        "developer_or_owner":  "Urban Construction \u0026 Development",
        "size":  "71 units 9 stories",
        "units":  71,
        "status":  "Sales underway near Court Square",
        "pitch_angle":  "Low-rise boutique PM pitch",
        "best_contact_path":  "Urban Construction \u0026 Development",
        "source":  "CityRealty",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "77eecb93-c870-459a-86cc-0c38d2cc6ef7",
        "priority":  "MEDIUM",
        "category":  "New Dev — Queens LIC",
        "target":  "Icon Condominium",
        "address":  "LIC",
        "developer_or_owner":  "INOA Architecture",
        "size":  "TBD",
        "units":  null,
        "status":  "Offering plan submitted July 2025 near Queensboro Plaza",
        "pitch_angle":  "Pre-construction advisory + eventual PM",
        "best_contact_path":  "INOA Architecture",
        "source":  "CityRealty",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "d4231471-5b9c-46a1-9489-68bb795bdb29",
        "priority":  "HIGH",
        "category":  "New Dev — Queens LIC",
        "target":  "The Cube",
        "address":  "42-53 24th Street LIC",
        "developer_or_owner":  "United Construction \u0026 Development",
        "size":  "217 units 14 stories",
        "units":  217,
        "status":  "Completion est 2027 retail component",
        "pitch_angle":  "Pitch for condo association PM post-sponsor",
        "best_contact_path":  "United Construction \u0026 Development",
        "source":  "CityRealty",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "1059e19e-ce8a-4e31-a7a7-2cbdc4167789",
        "priority":  "MEDIUM",
        "category":  "New Dev — Queens LIC",
        "target":  "30-25 Queens Boulevard",
        "address":  "30-25 Queens Boulevard LIC",
        "developer_or_owner":  "Baron Property Group",
        "size":  "561 units (451 rental + 110 condo) 46 stories",
        "units":  561,
        "status":  "$388.5M construction loan completion est 2028",
        "pitch_angle":  "Pitch PM for 110 condo units + retail",
        "best_contact_path":  "Baron Property Group",
        "source":  "CityRealty",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "3864c2b4-5a63-411d-abdd-66348ad92b07",
        "priority":  "MEDIUM",
        "category":  "New Dev — Queens LIC",
        "target":  "45-03 23rd Street",
        "address":  "45-03 23rd Street LIC",
        "developer_or_owner":  "Incoco Capital / Tavros / Charney Companies",
        "size":  "636 units 55 stories",
        "units":  636,
        "status":  "$525M loan Whole Foods + Chelsea Piers Fitness",
        "pitch_angle":  "Pitch as local PM partner for condo association",
        "best_contact_path":  "Incoco/Tavros/Charney",
        "source":  "CityRealty",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "8e6ab893-34fc-4055-a684-f3b716576cea",
        "priority":  "MEDIUM",
        "category":  "New Dev — Queens LIC",
        "target":  "Skyline Tower II (42-50 24th St)",
        "address":  "42-50 24th Street LIC",
        "developer_or_owner":  "United Construction \u0026 Development",
        "size":  "393 units 38 stories",
        "units":  393,
        "status":  "$57.5M land Feb 2025 completion 2028",
        "pitch_angle":  "Pre-completion PM pitch",
        "best_contact_path":  "United Construction \u0026 Development",
        "source":  "CityRealty",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "ecfb6031-cfea-4d25-aff2-dbeef9ef827b",
        "priority":  "MEDIUM",
        "category":  "New Dev — Williamsburg boutique",
        "target":  "185 Skillman Avenue",
        "address":  "East Williamsburg",
        "developer_or_owner":  "StudioSC",
        "size":  "Boutique condo",
        "units":  null,
        "status":  "Launching sales 2026",
        "pitch_angle":  "Pre-construction advisory",
        "best_contact_path":  "StudioSC",
        "source":  "Kimi research",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "a5bf7a81-fa02-4a74-bc54-d9d64e72b41e",
        "priority":  "HIGH",
        "category":  "New Dev — Williamsburg boutique",
        "target":  "109 Devoe Street",
        "address":  "109 Devoe Street Williamsburg",
        "developer_or_owner":  "StudioSC",
        "size":  "8 units",
        "units":  8,
        "status":  "Launching sales 2026",
        "pitch_angle":  "Small boutique direct sponsor outreach",
        "best_contact_path":  "StudioSC",
        "source":  "Kimi research",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "b8e6f212-a61d-4149-9391-1187ce204e0a",
        "priority":  "MEDIUM",
        "category":  "New Dev — Clinton Hill",
        "target":  "477 Washington Avenue",
        "address":  "477 Washington Ave Clinton Hill",
        "developer_or_owner":  "Z Architecture",
        "size":  "5-story condo",
        "units":  null,
        "status":  "Early stage",
        "pitch_angle":  "Ground-floor relationship opportunity",
        "best_contact_path":  "Z Architecture",
        "source":  "Kimi research",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "bcd58d77-07f2-48f6-aba1-364f97c66dad",
        "priority":  "HIGH",
        "category":  "Self-Managed — Compliance Pain",
        "target":  "CNYC Small Co-op/Condo Discussion Group",
        "address":  "NYC citywide",
        "developer_or_owner":  "Council of NY Cooperatives \u0026 Condos",
        "size":  "500+ buildings \u003c30 units",
        "units":  30,
        "status":  "Next meeting June 9 2026",
        "pitch_angle":  "Pitch boutique PM at small-building scale",
        "best_contact_path":  "Rebecca Poole Dir of Membership info@cnyc.coop",
        "source":  "cnyc.com",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "4986da92-2617-4e8f-a46e-197c08bf4a39",
        "priority":  "HIGH",
        "category":  "Self-Managed — Compliance Pain",
        "target":  "CNYC 46th Annual Conference",
        "address":  "NYC",
        "developer_or_owner":  "CNYC",
        "size":  "1000+ board members",
        "units":  null,
        "status":  "Fall 2026",
        "pitch_angle":  "Exhibit/sponsor — board members are decision makers",
        "best_contact_path":  "Rebecca Poole CNYC",
        "source":  "cnyc.com",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "f3ccb429-5092-47e7-be36-511fcf2f5206",
        "priority":  "HIGH",
        "category":  "Self-Managed — Compliance Pain",
        "target":  "Insurance Non-Renewal Buildings",
        "address":  "NYC citywide",
        "developer_or_owner":  "CNYC insurance advocacy list",
        "size":  "Hundreds",
        "units":  null,
        "status":  "Ongoing 2026 insurance crisis",
        "pitch_angle":  "Buildings need PM with strong vendor relationships — Camelot insurance mitigation",
        "best_contact_path":  "CNYC advocacy outreach",
        "source":  "cnyc.com",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "0fcbda47-89c2-40ad-a78c-3c2c578499a6",
        "priority":  "MEDIUM",
        "category":  "Self-Managed — Compliance Pain",
        "target":  "#4 Oil Conversion Buildings",
        "address":  "NYC",
        "developer_or_owner":  "CNYC #4 oil compliance list",
        "size":  "100+ remaining",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Boiler replacement = capital project mgmt opportunity",
        "best_contact_path":  "CNYC",
        "source":  "cnyc.com",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "7e78d7c0-fabf-47a5-8f70-916d214bf75e",
        "priority":  "HIGH",
        "category":  "Self-Managed — Compliance Pain",
        "target":  "Local Law 97 Penalty Buildings",
        "address":  "NYC",
        "developer_or_owner":  "NYC Open Data + CNYC dashboard",
        "size":  "50000+ buildings citywide",
        "units":  null,
        "status":  "Active enforcement",
        "pitch_angle":  "Pitch decarbonization consulting + PM bundle",
        "best_contact_path":  "NYC Open Data scrape + cold outreach",
        "source":  "nyc.gov",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "8cbe1808-5327-4e19-8df2-b55d97ca6992",
        "priority":  "HIGH",
        "category":  "Distressed — Acquisition + Mgmt",
        "target":  "Flagstar Bank Bankruptcy Portfolio",
        "address":  "Brooklyn / Queens / Manhattan / Bronx",
        "developer_or_owner":  "Various (Chapter 11)",
        "size":  "5100+ rent-stabilized units",
        "units":  null,
        "status":  "Dec 2026 auction bid deadline",
        "pitch_angle":  "Contact winning bidders SAME DAY post-acquisition",
        "best_contact_path":  "Monitor auction set Google Alerts",
        "source":  "Multi-Housing News",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "d84c89a6-4e89-45d5-a4bf-ab47ef35291d",
        "priority":  "HIGH",
        "category":  "Distressed — Acquisition + Mgmt",
        "target":  "Tax Lien Graveyard Trust Properties",
        "address":  "NYC",
        "developer_or_owner":  "Various distressed owners",
        "size":  "350+ multifamily buildings",
        "units":  null,
        "status":  "Land Bank takeover 2029",
        "pitch_angle":  "Position as interim stabilization manager",
        "best_contact_path":  "HPD relationship + new owner outreach",
        "source":  "nyc.gov",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "7fff5d47-2229-4640-9e58-b5be870be47e",
        "priority":  "MEDIUM",
        "category":  "Distressed — Acquisition + Mgmt",
        "target":  "TPT Reform Properties (Intro 657-2026)",
        "address":  "NYC",
        "developer_or_owner":  "New nonprofit owners",
        "size":  "Distressed rentals",
        "units":  null,
        "status":  "Active 2026 reform",
        "pitch_angle":  "Pitch nonprofit coalition + HPD relationship",
        "best_contact_path":  "HPD + reform coalition",
        "source":  "nyc.gov",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "5cfaa634-f6a9-4269-8571-20c77df9efda",
        "priority":  "HIGH",
        "category":  "Distressed — Acquisition + Mgmt",
        "target":  "Aging Co-op Sponsor Units",
        "address":  "Greenwich Village Carnegie Hill Morningside Hts",
        "developer_or_owner":  "Various individual sponsors",
        "size":  "Thousands of unsold shares",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Sponsors need PM for rental ops of unsold shares",
        "best_contact_path":  "StreetEasy keyword search Sponsor Unit / No Board Approval",
        "source":  "avenuelawfirm",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "19526b4d-f42e-4beb-918a-c243a75cfd2c",
        "priority":  "HIGH",
        "category":  "Institutional Developer",
        "target":  "Kahen Properties",
        "address":  "1026 Third Ave (The Remi)",
        "developer_or_owner":  "Kahen Properties",
        "size":  "108 units",
        "units":  108,
        "status":  "Sponsor-to-board transition + ongoing PM",
        "pitch_angle":  "Direct to Kahen development team",
        "best_contact_path":  "Kahen direct outreach",
        "source":  "Kimi research",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "e6a9a5ec-41c9-48bb-b45b-495d5d820093",
        "priority":  "MEDIUM",
        "category":  "Institutional Developer",
        "target":  "Toll Brothers City Living (Tribeca)",
        "address":  "351-355 Broadway Tribeca",
        "developer_or_owner":  "Toll Brothers",
        "size":  "98 units",
        "units":  98,
        "status":  "Active",
        "pitch_angle":  "National developer seeking local PM partner",
        "best_contact_path":  "Toll Brothers City Living NYC office",
        "source":  "Kimi research",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "fe870879-c84a-4f68-a4f9-fee1cbcb7df0",
        "priority":  "MEDIUM",
        "category":  "Institutional Developer",
        "target":  "Sackman Enterprises",
        "address":  "15 West 96th Street",
        "developer_or_owner":  "Sackman Enterprises",
        "size":  "16 ultra-luxury condos",
        "units":  null,
        "status":  "3000+ sqft units",
        "pitch_angle":  "Ultra-luxury PM for full-floor condos",
        "best_contact_path":  "Direct to Sackman",
        "source":  "Kimi research",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "f71d1c60-c7b5-4f83-8573-d9850d50c868",
        "priority":  "MEDIUM",
        "category":  "Institutional Developer",
        "target":  "Pi Capital Partners",
        "address":  "339 Fifth Avenue",
        "developer_or_owner":  "Pi Capital Partners",
        "size":  "TBD",
        "units":  null,
        "status":  "Pre-construction",
        "pitch_angle":  "Pre-construction PM advisory",
        "best_contact_path":  "Direct outreach Pi Capital",
        "source":  "Kimi research",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "f4d174a9-938c-45ab-861f-0e7097341d80",
        "priority":  "HIGH",
        "category":  "Competitive Takeaway",
        "target":  "711 West End Avenue",
        "address":  "711 West End Avenue UWS",
        "developer_or_owner":  "P2B Ventures (currently Kaled Mgmt)",
        "size":  "65-unit addition",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Competitive takeaway from Kaled Management",
        "best_contact_path":  "Board outreach as project completes",
        "source":  "Kimi research",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "e0cbd3f4-3f17-42c9-b856-f925208cdea6",
        "priority":  "HIGH",
        "category":  "Institutional Developer",
        "target":  "NY Lions Group / Albert Shirian",
        "address":  "42-06 27th Street LIC",
        "developer_or_owner":  "NY Lions Group",
        "size":  "110 units",
        "units":  110,
        "status":  "Active",
        "pitch_angle":  "Queens expansion opportunity",
        "best_contact_path":  "Direct to Albert Shirian",
        "source":  "Kimi research",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "af573706-5af7-425b-a281-4edb6639b763",
        "priority":  "MEDIUM",
        "category":  "Institutional Developer",
        "target":  "Bharat Patel / Sun Moon NY LLC",
        "address":  "100 Greenwich Street",
        "developer_or_owner":  "Sun Moon NY LLC",
        "size":  "192-unit hotel/residential",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Mixed-use PM pitch",
        "best_contact_path":  "Direct to Bharat Patel",
        "source":  "Kimi research",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "4eba7db8-80bb-4842-94d8-ddfab2185974",
        "priority":  "HIGH",
        "category":  "Institutional Developer",
        "target":  "Corigin Real Estate Group",
        "address":  "20 East End Avenue",
        "developer_or_owner":  "Corigin",
        "size":  "43 units $4.5M-$20M range",
        "units":  43,
        "status":  "Active",
        "pitch_angle":  "High-end condo PM",
        "best_contact_path":  "Direct to Corigin principals",
        "source":  "Kimi research",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "2a7d5372-00d3-476e-8e47-fc13a0f8db81",
        "priority":  "HIGH",
        "category":  "New Dev — Bronx Affordable",
        "target":  "The Peninsula Phase II",
        "address":  "Hunts Point South Bronx",
        "developer_or_owner":  "MHANY + Gilbane + community partners",
        "size":  "~250 units (740 total)",
        "units":  250,
        "status":  "Phase II completion 2026",
        "pitch_angle":  "Partner with MHANY as local PM subcontractor",
        "best_contact_path":  "MHANY development team",
        "source":  "Gilbane",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "bef66fd0-ba92-42c6-b6f8-f3789912404d",
        "priority":  "MEDIUM",
        "category":  "New Dev — Bronx Supportive",
        "target":  "Baez Place",
        "address":  "Claremont Bronx",
        "developer_or_owner":  "Community Access + Blue Sky Bronx LLC",
        "size":  "154 units",
        "units":  154,
        "status":  "Completed March 2026",
        "pitch_angle":  "Newly completed — supportive-services PM opportunity",
        "best_contact_path":  "Community Access leadership",
        "source":  "Governor.NY.gov",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "0bc9367b-8d4f-456b-a3c9-21a049d1f86d",
        "priority":  "MEDIUM",
        "category":  "New Dev — Queens Affordable",
        "target":  "Ocean Park Apartments",
        "address":  "Far Rockaway Queens",
        "developer_or_owner":  "Tredway",
        "size":  "602 units",
        "units":  602,
        "status":  "Renovation underway completion est 2026",
        "pitch_angle":  "Affordable housing PM — partner model",
        "best_contact_path":  "Tredway",
        "source":  "Merchants Capital",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "10c37d8c-531b-4019-9057-55b7cb8864a4",
        "priority":  "HIGH",
        "category":  "Competitive Takeaway",
        "target":  "Mega-firm Remote/Hybrid Boards",
        "address":  "NYC citywide",
        "developer_or_owner":  "Boards under FirstService / AKAM / Douglas Elliman PM",
        "size":  "Various",
        "units":  null,
        "status":  "Active 2026",
        "pitch_angle":  "Pitch: We still show up. White-glove in-person 24/7",
        "best_contact_path":  "Board president outreach via CNYC directory",
        "source":  "Camelot positioning",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "23cd07b4-cf74-44df-9c65-42b7a8d1947a",
        "priority":  "HIGH",
        "category":  "Competitive Takeaway",
        "target":  "DOB Violation Pileup Buildings",
        "address":  "NYC citywide",
        "developer_or_owner":  "Various boards",
        "size":  "Various",
        "units":  null,
        "status":  "2026",
        "pitch_angle":  "DOB violation remediation specialty pitch",
        "best_contact_path":  "Scrape NYC DOB BIS for repeat-violator buildings",
        "source":  "nyc.gov BIS",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "24d9e37b-0fdd-4e43-8c49-11b04c5e8cd2",
        "priority":  "HIGH",
        "category":  "Competitive Takeaway",
        "target":  "Local Law 97 Fine-Facing Buildings",
        "address":  "NYC citywide",
        "developer_or_owner":  "Various boards",
        "size":  "Various",
        "units":  null,
        "status":  "2024-2026 enforcement",
        "pitch_angle":  "We get you compliant not just managed",
        "best_contact_path":  "NYC LL97 Dashboard + cold outreach",
        "source":  "nyc.gov",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "8a501b03-e4c9-4570-8689-213e46b167c8",
        "priority":  "HIGH",
        "category":  "Competitive Takeaway",
        "target":  "FISP Facade-Delayed Buildings",
        "address":  "NYC citywide",
        "developer_or_owner":  "Various boards",
        "size":  "Various",
        "units":  null,
        "status":  "2026",
        "pitch_angle":  "Project mgmt + compliance bundle",
        "best_contact_path":  "DOB FISP database",
        "source":  "nyc.gov FISP",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "2e67032d-f227-4a2c-9772-339fa8025660",
        "priority":  "MEDIUM",
        "category":  "Competitive Takeaway",
        "target":  "32BJ Strike-Prep Buildings",
        "address":  "NYC citywide",
        "developer_or_owner":  "Various boards",
        "size":  "Various",
        "units":  null,
        "status":  "2026 contract season",
        "pitch_angle":  "Labor relations + ops continuity pitch",
        "best_contact_path":  "Industry intel + CNYC",
        "source":  "Camelot positioning",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "fbf77589-d10d-4e15-90f6-083e9e588957",
        "priority":  "HIGH",
        "category":  "Suburban — Westchester",
        "target":  "The Hudson at Croton-on-Hudson",
        "address":  "Croton-on-Hudson NY",
        "developer_or_owner":  "TBD",
        "size":  "~100 units",
        "units":  100,
        "status":  "Active leasing",
        "pitch_angle":  "Hudson Valley luxury — Camelot Westchester expansion",
        "best_contact_path":  "Direct to developer",
        "source":  "buywithbizzarro",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "399a7cb9-f4c6-411f-b7c3-d35e17bd19b8",
        "priority":  "HIGH",
        "category":  "Suburban — Westchester",
        "target":  "The Enclave at Armonk",
        "address":  "Armonk NY",
        "developer_or_owner":  "Toll Brothers",
        "size":  "TBD luxury",
        "units":  null,
        "status":  "Model home late spring 2026",
        "pitch_angle":  "National-developer-local-PM-partner pitch",
        "best_contact_path":  "Toll Brothers Westchester division",
        "source":  "realestatehudsonvalleyny",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "8d3090b6-28cc-4ce9-ac35-6fda06e0b9df",
        "priority":  "MEDIUM",
        "category":  "Suburban — Westchester",
        "target":  "Tavo Development project",
        "address":  "Westchester (TBD)",
        "developer_or_owner":  "Tavo Development (arch Teo Siguenza)",
        "size":  "TBD",
        "units":  null,
        "status":  "Fall 2026 completion",
        "pitch_angle":  "Pre-completion PM pitch",
        "best_contact_path":  "Direct to Tavo Development",
        "source":  "realestatehudsonvalleyny",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "2c9a4f2e-86da-4e0b-a0fe-a8abee6b0394",
        "priority":  "MEDIUM",
        "category":  "Suburban — Westchester",
        "target":  "Villa BXV",
        "address":  "Bronxville NY",
        "developer_or_owner":  "Existing 2018 building",
        "size":  "53 units one- to three-bed + penthouses",
        "units":  53,
        "status":  "Stabilized — competitive takeaway",
        "pitch_angle":  "Board outreach for management review",
        "best_contact_path":  "buywithbizzarro",
        "source":  null,
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "00b25e48-a9fc-4516-b4e0-148fddd1a475",
        "priority":  "MEDIUM",
        "category":  "Suburban — Westchester",
        "target":  "St Regis Residences",
        "address":  "Rye NY",
        "developer_or_owner":  "Existing",
        "size":  "95 units 55+ community",
        "units":  95,
        "status":  "Stabilized",
        "pitch_angle":  "Competitive takeaway luxury 55+ community",
        "best_contact_path":  "Board / developer direct",
        "source":  "buywithbizzarro",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "5eefa75d-7dcb-4a9f-97ea-1e771626b987",
        "priority":  "HIGH",
        "category":  "Suburban — NJ",
        "target":  "Daisy NJ HOA expansion territory",
        "address":  "Northern NJ HOAs",
        "developer_or_owner":  "Daisy (competitor — territory map)",
        "size":  "Various",
        "units":  null,
        "status":  "2026 active expansion",
        "pitch_angle":  "Counter-positioning vs Daisy in NJ HOA market",
        "best_contact_path":  "Northern NJ HOA boards directly",
        "source":  "njbiz",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "c293e920-2406-438f-a2a4-df3e284633e9",
        "priority":  "HIGH",
        "category":  "Suburban — NJ South",
        "target":  "South Jersey HOAs (Cherry Hill Camden)",
        "address":  "Cherry Hill NJ + Camden County",
        "developer_or_owner":  "Various HOAs",
        "size":  "Various",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Competitive takeaway from CAMCO / Associa / Corner / Realty Solutions",
        "best_contact_path":  "Direct board outreach",
        "source":  "njrealtysolutions",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "0d07aead-2747-49f5-8ed0-a9c8a148d7d1",
        "priority":  "MEDIUM",
        "category":  "Suburban — NJ South",
        "target":  "Jersey City Reserve Study Compliance",
        "address":  "Jersey City Hudson County",
        "developer_or_owner":  "Buildings 200+ units / 25+ years old",
        "size":  "200+ unit HOAs",
        "units":  null,
        "status":  "S2760 \u0026 S3992 compliance 2026",
        "pitch_angle":  "Pitch compliance + PM bundle",
        "best_contact_path":  "NJ HOA director outreach",
        "source":  "propfusion",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "97ca93e7-41d6-4149-94c6-e2c73088c239",
        "priority":  "HIGH",
        "category":  "Florida — Compliance Pain",
        "target":  "SIRS-Stressed Condo Associations",
        "address":  "Statewide FL",
        "developer_or_owner":  "Owner-controlled assocs 3+ stories",
        "size":  "Hundreds-thousands",
        "units":  null,
        "status":  "SIRS deadlines Dec 2025/2026 + milestone insp every 10 yrs",
        "pitch_angle":  "Replacement mgmt for non-compliant associations facing $500/day fines + special magistrate liens",
        "best_contact_path":  "FCAP membership + targeted boards",
        "source":  "M2E / criterium-cromer / fpat",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "fb0566fd-b8ed-451f-abbf-3df6f1d17017",
        "priority":  "HIGH",
        "category":  "Florida — Compliance Pain",
        "target":  "Coastal Buildings within 3 mi of coast",
        "address":  "FL coastline",
        "developer_or_owner":  "Buildings 25+ years old",
        "size":  "Thousands",
        "units":  null,
        "status":  "Required milestone inspection",
        "pitch_angle":  "Replacement PM as associations panic over compliance",
        "best_contact_path":  "Coastal county property records",
        "source":  "buildingmavens",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "dddb2a91-5cf7-4864-82a4-c050b7f6c120",
        "priority":  "HIGH",
        "category":  "Florida — Compliance Pain",
        "target":  "Pre-2025 Reserve-Waiver Buildings",
        "address":  "Statewide FL",
        "developer_or_owner":  "SIRS-required associations",
        "size":  "Many",
        "units":  null,
        "status":  "Can no longer waive/reduce reserve contributions",
        "pitch_angle":  "Capital project mgmt + PM bundle pitch",
        "best_contact_path":  "Direct association outreach",
        "source":  "propfusion",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "5cfea5c3-12b2-4841-94d8-ebe87baee143",
        "priority":  "MEDIUM",
        "category":  "Florida — Distress",
        "target":  "Older High-Rise Condos w/ Special Assessments",
        "address":  "Miami Beach Fort Lauderdale Naples",
        "developer_or_owner":  "Various 1970s-90s buildings",
        "size":  "Various",
        "units":  null,
        "status":  "Active distress wave 2026",
        "pitch_angle":  "Replacement PM as owners protest",
        "best_contact_path":  "Property managers reports + local press",
        "source":  "Surfside reform fallout",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "c97ba3d2-5e6e-4849-8624-e7176b895b40",
        "priority":  "HIGH",
        "category":  "Florida — New Dev",
        "target":  "Florida HOA \u0026 Condo Mgmt 2026 Industry Report Lookalikes",
        "address":  "Statewide FL",
        "developer_or_owner":  "Various boutique developers",
        "size":  "Various",
        "units":  null,
        "status":  "May 2026 report",
        "pitch_angle":  "Use report\u0027s top-rated firms list to identify boards moving away from underperformers",
        "best_contact_path":  "PRWeb FL HOA report",
        "source":  "prweb",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "1816be2d-3d98-44e8-8fe6-588d2e730bc3",
        "priority":  "MEDIUM",
        "category":  "Florida — Acquisition",
        "target":  "Florida PM Firms for Sale (50+ on BizQuest)",
        "address":  "Statewide FL",
        "developer_or_owner":  "Various small firms",
        "size":  "Under $10M revenue typically",
        "units":  null,
        "status":  "Active listings",
        "pitch_angle":  "Tuck-in acquisition — buy a Florida book of business",
        "best_contact_path":  "BizQuest FL listings",
        "source":  "bizquest",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "c3723d6e-c70e-4478-bbff-d8480a1a0329",
        "priority":  "HIGH",
        "category":  "PM Firm Acquisition",
        "target":  "NY PM Firms for Sale (BizBuySell)",
        "address":  "NY statewide",
        "developer_or_owner":  "Various boutique firms",
        "size":  "Sub-$10M revenue",
        "units":  null,
        "status":  "Active 280 nationwide",
        "pitch_angle":  "Acquire NY book of business",
        "best_contact_path":  "BizBuySell NY listings",
        "source":  "bizbuysell",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "da9a2b1b-d688-4c35-aff9-85c5e9b5c8ce",
        "priority":  "MEDIUM",
        "category":  "PM Firm Acquisition",
        "target":  "NJ PM Firms for Sale (BizQuest 5 listings)",
        "address":  "NJ statewide",
        "developer_or_owner":  "Various small firms",
        "size":  "Various",
        "units":  null,
        "status":  "Active listings",
        "pitch_angle":  "Acquire NJ book of business",
        "best_contact_path":  "BizQuest NJ listings",
        "source":  "bizquest",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "29772f60-7b7b-4143-9727-01f32c73deba",
        "priority":  "MEDIUM",
        "category":  "PM Firm Acquisition",
        "target":  "LoopNet PM Business Listings",
        "address":  "Multi-state",
        "developer_or_owner":  "Various",
        "size":  "Various",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Acquire commercial PM firm",
        "best_contact_path":  "LoopNet biz listings",
        "source":  "loopnet",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "ee76d4b7-84b7-4bef-968a-0f7584a9bc7b",
        "priority":  "MEDIUM",
        "category":  "Out-of-the-box",
        "target":  "NYC Public Administrator estate auctions",
        "address":  "NYC",
        "developer_or_owner":  "County Public Admin",
        "size":  "Various estate properties",
        "units":  null,
        "status":  "Ongoing",
        "pitch_angle":  "Estate-property PM during probate (7-9 months) + post-sale",
        "best_contact_path":  "Contact NY County Public Admin",
        "source":  "nyc.gov",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "ac6be418-8f26-4c4f-8640-1e65b2a7ef40",
        "priority":  "MEDIUM",
        "category":  "Out-of-the-box",
        "target":  "Astoria 21-unit multifamily bankruptcy",
        "address":  "29th Street Astoria Queens",
        "developer_or_owner":  "Bankruptcy estate",
        "size":  "21 residential units 13000 sqft",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Post-acquisition PM pitch",
        "best_contact_path":  "Bankruptcy court filings",
        "source":  "Empathy",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "0c20e5ab-b00e-43be-b7c8-02264e9029b9",
        "priority":  "HIGH",
        "category":  "Referral Channel",
        "target":  "Real Property Management NY Gold",
        "address":  "NYC",
        "developer_or_owner":  "Realtor referral program",
        "size":  "$250/referral",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Reverse referral — Camelot send PM referrals get $250 + relationship",
        "best_contact_path":  "Realtor referral program",
        "source":  "rpmnewyorkgold",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "5b53a97f-5eab-4e2e-9b53-22bd7a78329a",
        "priority":  "HIGH",
        "category":  "Referral Channel",
        "target":  "Estate Planning + Probate Attorneys",
        "address":  "NYC",
        "developer_or_owner":  "Cullen and Dykman McLaughlin \u0026 Stern Tannenbaum Helpern Jules M Haas Stephen Bilkis",
        "size":  "Various",
        "units":  null,
        "status":  "Active referral channel",
        "pitch_angle":  "Trust + estate property mgmt referrals — pitch CLE + lunch",
        "best_contact_path":  "Direct partner-by-name outreach",
        "source":  "nycprobatelawyer",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "faa88621-ee8f-4931-a954-85ebb3c67a72",
        "priority":  "HIGH",
        "category":  "Referral Channel",
        "target":  "NYC Bar Legal Referral Service",
        "address":  "42 West 44th Street NYC",
        "developer_or_owner":  "NYC Bar",
        "size":  "Connects attorneys to clients",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Become preferred PM partner for estate/landlord-tenant attorneys",
        "best_contact_path":  "NYC Bar Referral Service",
        "source":  "nycbar.org",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "a8794646-e4d8-4741-91ec-09e445b56729",
        "priority":  "HIGH",
        "category":  "Referral Channel",
        "target":  "Skyline Properties (commercial brokerage)",
        "address":  "NYC",
        "developer_or_owner":  "Skyline Properties",
        "size":  "Has own commercial PM — competitor + potential overflow",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Overflow PM referrals from non-fit accounts",
        "best_contact_path":  "Skyline Properties NYC",
        "source":  "clutch.co",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "7a8c9ee5-04db-4c0f-9577-0ff806c74fd5",
        "priority":  "HIGH",
        "category":  "Referral Channel",
        "target":  "NAI Global brokerage NYC office",
        "address":  "NYC",
        "developer_or_owner":  "NAI Global",
        "size":  "Commercial brokerage no NYC PM arm",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "PM referrals from commercial brokerage",
        "best_contact_path":  "NAI Global NY office",
        "source":  "naiglobal",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "95ade780-4624-42b6-a5dd-dc1c2131b6e3",
        "priority":  "MEDIUM",
        "category":  "Referral Channel",
        "target":  "Boutique residential brokerages without PM arms",
        "address":  "NYC + Suburbs",
        "developer_or_owner":  "Many",
        "size":  "Various",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Build referral pipeline from listing agents whose owner-clients need mgmt",
        "best_contact_path":  "Direct outreach to broker-owners",
        "source":  "clutch.co",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "1ce5cf1e-9863-4d87-ad79-bd05d50a2208",
        "priority":  "HIGH",
        "category":  "Family Office Channel",
        "target":  "NYC Family Office Directory",
        "address":  "NYC",
        "developer_or_owner":  "Multiple SFOs/MFOs",
        "size":  "Various $50M-$200M RE holdings",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Pitch direct RE mgmt outsourcing",
        "best_contact_path":  "Family Office Access directory",
        "source":  "familyofficeaccess",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "16f79361-42b8-4855-a57a-667b9bcbc914",
        "priority":  "MEDIUM",
        "category":  "Family Office Channel",
        "target":  "Cresset Capital NYC office",
        "address":  "NYC",
        "developer_or_owner":  "Cresset Capital multi-family office",
        "size":  "Various",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Cresset clients with NYC RE may need local PM",
        "best_contact_path":  "Direct partner outreach Cresset NY",
        "source":  "cressetcapital",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "88bcdc7c-b854-4286-aa04-dd5a1d13b9b7",
        "priority":  "MEDIUM",
        "category":  "Family Office Channel",
        "target":  "JMC Family Office",
        "address":  "NYC",
        "developer_or_owner":  "JMC Family Office",
        "size":  "Various",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Direct family office relationship",
        "best_contact_path":  "Direct JMC outreach",
        "source":  "jmcfamilyoffice",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "63101767-47bb-4db4-a69f-c8604d93a181",
        "priority":  "MEDIUM",
        "category":  "Family Office Channel",
        "target":  "Baker Tilly Real Estate Services for Family Offices",
        "address":  "NYC",
        "developer_or_owner":  "Baker Tilly",
        "size":  "Various",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Cross-referral with Baker Tilly\u0027s RE family office clients",
        "best_contact_path":  "Baker Tilly RE practice lead",
        "source":  "bakertilly",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "e5e62948-d2cb-49f7-89a9-18cc2824d9b4",
        "priority":  "HIGH",
        "category":  "Family Office Channel",
        "target":  "Brown Brothers Harriman Multi-Family Office",
        "address":  "NYC",
        "developer_or_owner":  "BBH MFO",
        "size":  "Various large family RE holdings",
        "units":  null,
        "status":  "Active",
        "pitch_angle":  "Family office clients with single-asset RE may need local mgmt",
        "best_contact_path":  "BBH Capital Partners team",
        "source":  "bbh.com",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    },
    {
        "id":  "27a1c0ee-3d56-41df-9c26-7c6d72c8a457",
        "priority":  "HIGH",
        "category":  "Industry Body",
        "target":  "Queens Bronx Building Association (current member)",
        "address":  "Queens + Bronx",
        "developer_or_owner":  "QBBA",
        "size":  "200+ buildings represented",
        "units":  null,
        "status":  "Active membership",
        "pitch_angle":  "Upgrade Camelot\u0027s QBBA visibility for QQ/BX boards",
        "best_contact_path":  "QBBA events + sponsorship",
        "source":  "QBBA",
        "imported_at":  "2026-05-25T18:00:00.000Z"
    }
];
